---
- name: Download nomad binaries
  become: true
  ansible.builtin.unarchive:
    src: "https://releases.hashicorp.com/nomad/{{ nomad_version }}/nomad_{{ nomad_version }}_linux_amd64.zip"
    dest: /usr/bin/
    mode: 0755
    remote_src: yes
- name: Download CNI
  become: true
  ansible.builtin.unarchive:
    src: "https://github.com/containernetworking/plugins/releases/download/v0.9.1/cni-plugins-linux-amd64-v0.9.1.tgz"
    dest: /opt/cni/bin/
    mode: 0755
    remote_src: yes