# ---
- name: Base dependencies
  hosts: all
  become: true
  roles:
    - init
    #- docker
- name: Nomad installation
  hosts: all
  become: true
  serial: 3
  roles:
    - nomad
  vars:
    nomad_version: "1.5.5"
    aws_region: "eu-west-1"
    profile: default
- name: Credential process
  hosts: all
  become: true
  vars:
    aws_region: "eu-west-1"
    profile: default
  roles:
    - credential-process
