---
- name: Base dependencies
  hosts: all
  become: true
  roles:
    - init
    #- docker
- name: Nomad installation
  hosts: all
  become: true
  serial: 3
  roles:
    - nomad
  vars:
    region: "eu-west-1"
    nomad_version: "1.5.5"
    aws_profile: "default"
    acm_pca_arn: "{{ lookup('aws_ssm', '/infrastructure/pca/arn' )}}"
    cluster_url: "{{ lookup('aws_ssm', '/infrastructure/nomad/endpoint' )}}"
- name: Credential process
  hosts: all
  become: true
  vars:
    region: "eu-west-1"
    iam_any_trust_anchor_arn: "{{ lookup('aws_ssm', '/infrastructure/trust_anchor/arn' )}}"
    iam_any_profile_arn: "{{ lookup('aws_ssm', '/infrastructure/profile/arn' )}}"
    iam_any_role_arn: "{{ lookup('aws_ssm', '/infrastructure/role/arn' )}}"
  roles:
    - credential-process
